---
title: Make a face
hero_image: images/banner.png
description: Design and draw a face or mask using geometric shapes
meta_title: Python coding projects for kids and teens | Make a face
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Write Python code to draw a face or mask using geometric shapes.
version: 4
listed: false
copyedit: false
last_tested: "2024-06-04"
steps:
  - title: You will make
  - title: Choose a theme
  - title: Face shape
    completion:
      - engaged
  - title: Add eyes
  - title: Add a mouth
  - title: Add more details
    completion:
      - internal
  - title: Upgrade your project
  - title: Share
  - title: What next?
